### PR TITLE
Remove secure endpoint parameter, as of s3proxy 1.5 this requires two…

### PR DESCRIPTION
**Pull request by jschlather**
… more parameters to be passed as well.

### CODE REVIEW

**Comment by bdarfler** [comment]
I'm confused. Does this require an upgrade of the s3proxy dep? Also does this require README changes for these "two new parameters"?

**Comment by jschlather** [comment]
No, the secure-endpoint is currently superfluous, as in we don't need it and don't use it. I'm using a snapshot of 1.5.0 in a project, because I needed multipart uploads. In this version, s3proxy won't even start if you pass it a secure endpoint parameter without the keystore as well. In 1.3, which we currently default to the secure endpoint parameter is unneeded.

**Comment by bdarfler** [comment]
Hmm. I think this sounds fine but I don't have all the details. I defer to @jsolmon

**Comment by jsolmon** [comment]
Would this break connecting via https? https://github.com/andrewgaul/s3proxy/blob/8b2a869341f3b5bb5e7fb23e89ab6cedb8802b69/src/main/java/org/gaul/s3proxy/S3Proxy.java#L91

We could make it configurable rather than removing it completely.

**Comment by jschlather** [comment]
The version of the code you're looking at will throw an exception, because the keystore parameters aren't passed. Anyway, if you guys are nervous about this change I'd rather just publish a fork to our local artifactory. So I'm going to do that.

**Pull request closed without merging**
